version: '3.8'

services:
  pulsar:
    image: apachepulsar/pulsar:3.2.0
    profiles: ["pulsar"]
    container_name: pulsar-alpespartners
    restart: unless-stopped
    ports:
      - "6650:6650"   
      - "8080:8080"  
      - "8082:8081"   
    command: bin/pulsar standalone
    environment:
      - PULSAR_MEM=-Xms512m -Xmx512m -XX:MaxDirectMemorySize=512m
    volumes:
      - pulsar_data:/pulsar/data
    healthcheck:
      test: ["CMD", "bin/pulsar-admin", "clusters", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  mongodb:
    image: mongo:7.0
    profiles: ["alpespartners", "mongodb"]
    container_name: alpespartners-mongodb
    ports:
      - "27017:27017"
    command: mongod --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: alpespartners
    volumes:
      - ./mongo_data:/data/db
    networks:
      - alpespartners-network
  marketing:
    build:
      context: .
      dockerfile: marketing.Dockerfile
    profiles: ["alpespartners"]
    container_name: marketing
    restart: unless-stopped
    command: 
      - sh
      - -c
      - |
        python -m debugpy --listen 0.0.0.0:5678 -m flask --app src/marketing/api run --host=0.0.0.0 -p 8000 --reload
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DATABASE_TYPE=mongodb
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/alpespartners?authSource=admin
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongodb
    networks:
      - alpespartners-network
  tracking:
    build:
      context: .
      dockerfile: tracking.Dockerfile
    profiles: ["alpespartners"]
    container_name: tracking
    restart: unless-stopped
    command: 
      - sh
      - -c
      - |
        python -m debugpy --listen 0.0.0.0:5678 -m flask --app src/tracking/api run --host=0.0.0.0 -p 8000 --reload
    ports:
      - "8001:8000"
      - "5679:5678"
    environment:
      - DATABASE_TYPE=mongodb
      - MONGODB_URI=mongodb://admin:admin123@mongodb:27017/alpespartners?authSource=admin
      - PYTHONUNBUFFERED=1
    depends_on:
      - mongodb
    networks:
      - alpespartners-network

networks:
  alpespartners-network:
    driver: bridge

volumes:
  pulsar_data:
    driver: local
  mongodb_data:
    driver: local
