# ============================
# Microservicio: bff
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bff-service
  template:
    metadata:
      labels:
        app: bff-service
    spec:
      containers:
        - name: bff-container
          image: us-central1-docker.pkg.dev/tutoriales-miso/alpespartners/bff:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
            - name: BROKER_HOST
              value: "pulsar-mini-proxy.pulsar.svc.cluster.local"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: MARKETING_SERVICE_URL
              value: "http://marketing-service"
            - name: TRACKING_SERVICE_URL
              value: "http://tracking-service"
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: bff-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    requestPath: "/health"
    type: HTTP
    port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "bff-backend-config"}'
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: bff-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      # nodePort: 30004