# ============================
# Microservicio: bff
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bff-service
  namespace: default
spec:
  replicas: 3  # Increased replicas for load distribution
  selector:
    matchLabels:
      app: bff-service
  template:
    metadata:
      labels:
        app: bff-service
    spec:
      containers:
        - name: bff-container
          image: us-central1-docker.pkg.dev/tutoriales-miso/alpespartners/bff:latest
          resources:
            requests:
              memory: "512Mi"  # Increased from 64Mi
              cpu: "1000m"     # Increased from 250m (1 CPU core)
            limits:
              memory: "1Gi"    # Increased from 128Mi
              cpu: "2000m"     # Increased from 500m (2 CPU cores)
          ports:
            - containerPort: 8000
          env:
            - name: BROKER_HOST
              value: "pulsar-mini-proxy.pulsar.svc.cluster.local"
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: MARKETING_SERVICE_URL
              value: "http://marketing-service"
            - name: TRACKING_SERVICE_URL
              value: "http://tracking-service"
          # Add readiness and liveness probes for better reliability
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: bff-backend-config
spec:
  healthCheck:
    checkIntervalSec: 15  # More frequent health checks
    timeoutSec: 3         # Reduced timeout
    requestPath: "/health"
    type: HTTP
    port: 8000
  # Add connection draining for graceful shutdowns
  connectionDraining:
    drainingTimeoutSec: 60
---
apiVersion: v1
kind: Service
metadata:
  name: bff-service
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "bff-backend-config"}'
spec:
  # type: NodePort
  type: LoadBalancer
  selector:
    app: bff-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      # nodePort: 30004