# ============================
# Microservicio: comisiones
# ============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comisiones-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comisiones-service
  template:
    metadata:
      labels:
        app: comisiones-service
    spec:
      containers:
        - name: comisiones-container
          image: us-central1-docker.pkg.dev/tutoriales-miso/alpespartners/comisiones:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongodb-root-password
            - name: MONGODB_HOST
              value: "mongodb.default.svc.cluster.local"
            - name: MONGODB_PORT
              value: "27017"
            - name: MONGODB_DATABASE
              value: "alpespartners"
            - name: BROKER_HOST
              value: "pulsar-mini-proxy.pulsar.svc.cluster.local"
            - name: PYTHONUNBUFFERED
              value: "1"
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: comisiones-backend-config
spec:
  healthCheck:
    checkIntervalSec: 30
    timeoutSec: 5
    requestPath: "/health"
    type: HTTP
    port: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: comisiones-service
  namespace: default
  annotations:
    cloud.google.com/backend-config: '{"default": "comisiones-backend-config"}'
spec:
  type: NodePort
  selector:
    app: comisiones-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30003
